<?php

/**
 * @file
 * Provides a calendar filter entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function calendar_filter_theme() {
  return [
    'calendar_filter' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for calendar filter templates.
 *
 * Default template: calendar-filter.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the calendar filter information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_calendar_filter(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
